### ISSUE TITLE
How to modify for my use case?

### ISSUE THREAD

**Issue by BeatriceThalo** [drauggres/ws-scrcpy#1]
Is the below modification for my use case possible and what would be the to-do list of steps and/or needed research?

What current project does:
Allows a real android device to be connected to a viewer device.
Allows installing an apk onto the real device copied from the viewer device, show the screen of the real android device on the viewer device, and send UI events from the viewer device to the real device's handlers.
The devices can be wired together via USB or wireless if both connected to the same wifi network.
The project's UI (client) running on the viewer device installs the project's jar/apk (server) onto the real device. Therefore the server is only needed for Android OS. The client [where original scrscpy is available in Win/Mac/Linux binaries] is Chrome for Windows or any Chrome?

What my use case needs:
Allows a real android device (Android VR Headset) to be connected to a viewer device (Desktop or Tablet).
Allows installing an apk onto the real device copied from the viewer device, show the screen of the real android device (only one eye) on the viewer device, and (bonus) send UI events from the viewer device to the real device's handlers.
The devices will be wired together via USB. A wifi network does not exist in the field, but if absolutely required to achieve our goals, could be provided.
The project's UI (client) running on the viewer device installs the project's jar/apk (server) onto the real device. Therefore the server is only needed for Android OS. The client is ideally coded in a web codebase for Electron to make win/mac/linux chromium binaries and for Cordova to make iOS/android binaries.

**Comment by drauggres** [comment]
Hi.
First of all: this project is only a prototype and could be used only as first step in your research (it is not ready for production in any way).

> The client [where original scrscpy is available in Win/Mac/Linux binaries] is Chrome for Windows or any Chrome?

Any modern browser on any platform (I was able to run at least one of the decoders on Linux/Mac/Windows in Chrome/Safari/Firefox and also on Chrome/SamsungBrowser on Android).

> show the screen of the real android device (only one eye) on the viewer device

For one-eye case there is a `crop` parameter: https://github.com/drauggres/ws-scrcpy/blob/cc991797e3989e866c19878993f391346a05063b/src/VideoSettings.ts#L15
But there is no way to set it from the current UI.
Also you can pass `crop` argument to scrcpy server ("no-crop" by default: "`-`", argument format: https://github.com/Genymobile/scrcpy#crop): 

https://github.com/drauggres/ws-scrcpy/blob/cc991797e3989e866c19878993f391346a05063b/src/server/ServerDeviceConnection.ts#L12

>  and (bonus) send UI events from the viewer device to the real device's handlers.

Can't really comment on this, I don't know what events you may possibly need on Android VR Headset. Looks like totally different use case unlike smartphone/tablet.
You will probably need to modify scrcpy server to be able to inject your specific events.

> The devices will be wired together via USB. A wifi network does not exist in the field, but if absolutely required to achieve our goals, could be provided.

You could forward websocket-server port to the client, since they are going to be connect via USB anyway. Something like `adb forward tcp:8886 tcp:8886` and then connect to `ws://127.0.0.1:8886`

>The client is ideally coded in a web codebase for Electron to make win/mac/linux chromium binaries and for Cordova to make iOS/android binaries.

This project consist of three parts:
1. "Streaming server" on device (modified scrcpy)
2. HTTP server on machine with adb server ([this file](https://github.com/drauggres/ws-scrcpy/blob/master/src/server/ServerDeviceConnection.ts)).
3. Web client

You don't need this specific (2) HTTP server, it is possible to use any other HTTP server to ship static clients files (I wanted to automatically install and run scrcpy on every device connected to the machine).
If you want the client to be web-based there is no need to package it in app, old-good web-site is fine.

Few important things to know:
- scrcpy server is NOT installed on the device permanently
- you MUST install and run it from adb (with `Developer options` enabled on the device)

Hope this helps.
